# Generated by Django 5.0.1 on 2024-01-24 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info_about', models.TextField(blank=True, null=True, verbose_name='содержание')),
            ],
            options={
                'verbose_name': 'Описание приложения',
                'verbose_name_plural': 'описании приложения',
                'db_table': 'Information',
            },
        ),
        migrations.DeleteModel(
            name='Content',
        ),
    ]
